name: Check branch
run-name: 'Check branch: `${{ github.event.pull_request.head.ref || github.ref_name }}`'

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  build:
    if: github.event.push || github.event.pull_request.draft == false
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/aaimio/application-hotkeys
          push: never
          runCmd: |
            pnpm lint
            pnpm build
